# Generated by Django 5.1.2 on 2024-11-05 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTransport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('current_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InTransitTransport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('current_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('current_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.TextField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamagedOrLostPackages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredPackages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PackagesDelivered',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PackagesInSystem',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Delivered to Warehouse', 'Deliveredtowarehouse'), ('Lost', 'Lost'), ('Damaged', 'Damaged'), ('Delivery Complete', 'Deliveredtofinal')], default='Registered', max_length=70)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagestatus_set', to='tracking.package')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DTW', 'Dispatchtowarehouse'), ('WTW', 'Warehousetowarehouse'), ('WTD', 'Warehousetodelivery')], default='WTW', max_length=70)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.transport')),
            ],
        ),
        migrations.CreateModel(
            name='PackagesInTransit',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FR', 'Fragile'), ('BK', 'Bulk'), ('PR', 'Priority'), ('PE', 'Perishable'), ('LI', 'Live')], default='FR', max_length=70)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('dispatch_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.customer')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.transport')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracking.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_addresses', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DTW', 'Dispatchtowarehouse'), ('WTW', 'Warehousetowarehouse'), ('WTD', 'Warehousetodelivery')], default='WTW', max_length=70)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.transport')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_warehouse', to='tracking.warehouse')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_warehouse', to='tracking.warehouse')),
            ],
        ),
    ]
