# Generated by Django 5.1.2 on 2024-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
