# Generated by Django 5.1.2 on 2024-11-06 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_package_estimated_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagesintransit',
            old_name='warehouse',
            new_name='warehouse_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Please enter a valid email address with '@'.", regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
